export default [
  {
    id: "XjCp6bUp__M",
    author: "Humane Hancock",
    title: "The Vegan Blind Spot",
    duration: "19:21",
  },
  {
    id: "1Dp6gObE9eA",
    author: "Animal Ethics",
    title: "Wild animal suffering: an introduction",
    duration: "10:10",
  },
  {
    id: "m9pCbH7BtcI",
    author: "Humane Hancock",
    title: "Vegans And Meat-Eaters Both Make This Mistake",
    duration: "16:14",
  },
  {
    id: "n3H4UtR_eak",
    author: "Wild Animal Initiative",
    title: "Wild Animal Welfare",
    duration: "33:38",
  },
  {
    id: "g-7cLXyMp8E",
    author: "Humane Hancock",
    title: "The Truth About Yellowstone",
    duration: "16:59",
  },
  {
    id: "VPzvWKOzWjY",
    author: "Centre for Effective Altruism",
    title: "How evolution can help us understand wild animal welfare",
    duration: "22:56",
  },
  {
    id: "hvDlYnCejHk",
    author: "Humane Hancock",
    title: "How a Vegan World Might Contain MORE Suffering",
    duration: "17:13",
  },
  {
    id: "AzFwOnYPV9U",
    author: "Animal Ethics",
    title: "Animal ethics and environmental ethics",
    duration: "9:24",
  },
  {
    id: "cp1qpzXe2Yw",
    author: "Humane Hancock",
    title: "How to SOLVE Wild Animal Suffering",
    duration: "29:25",
  },
  {
    id: "1dl_eHonR0w",
    author: "Animal Ethics",
    title: "Various ways to help wild animals in need",
    duration: "11:07",
  },
  {
    id: "_TaFwHa5ZRs",
    author: "Humane Hancock",
    title: "Cosmic Skeptic on Wild Animal Suffering",
    duration: "1:12:45",
  },
  {
    id: "K7E6IB9rw6c",
    author: "LSE Philosophy",
    title: "A beginner’s guide to wild animal suffering",
    duration: "21.29",
  },
  {
    id: "Cv9ftiEvSpA",
    author: "Humane Hancock",
    title: "Why I Stopped Idolizing David Attenborough",
    duration: "21:23",
  },
];
